# Development environment overrides
# Use with: helm install brahminykite ./helm/brahminykite -f ./helm/brahminykite/values-dev.yaml

# Reduce replicas for development
services:
  replicaCount: 1
  empirical:
    replicaCount: 1
  contextual:
    replicaCount: 1
  consistency:
    replicaCount: 1
  powerDynamics:
    replicaCount: 1
  utility:
    replicaCount: 1
  evolution:
    replicaCount: 1

api:
  replicaCount: 1
  env:
    LOG_LEVEL: "DEBUG"
    CORS_ORIGINS: "*"

# Reduce resource requirements
services:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

api:
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "300m"

# Use local domains
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: api.brahminykite.local
      paths:
        - path: /
          pathType: Prefix
          service: api
          port: 8000
    - host: grafana.brahminykite.local
      paths:
        - path: /
          pathType: Prefix
          service: grafana
          port: 3000
    - host: prometheus.brahminykite.local
      paths:
        - path: /
          pathType: Prefix
          service: prometheus-server
          port: 80
  tls: []

# Reduce storage for dev
postgresql:
  primary:
    persistence:
      size: 2Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

redis:
  master:
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

prometheus:
  server:
    persistentVolume:
      size: 2Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"

grafana:
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Disable autoscaling for dev
autoscaling:
  enabled: false

# Enable debug logging
logging:
  level: DEBUG

# Enable profiling for development
monitoring:
  profiling:
    enabled: true

# Development environment
environment: development