apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brahminykite.fullname" . }}-secrets
  namespace: {{ include "brahminykite.namespace" . }}
  labels:
    {{- include "brahminykite.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  {{- if not .Values.postgresql.enabled }}
  # External PostgreSQL password
  postgres-password: {{ .Values.externalPostgresql.password | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.redis.enabled) .Values.externalRedis.password }}
  # External Redis password
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
  # JWT secret for API auth
  jwt-secret-key: {{ .Values.api.jwtSecretKey | default (randAlphaNum 32) | b64enc | quote }}
  # Service API key for inter-service auth
  service-api-key: {{ .Values.api.serviceApiKey | default (randAlphaNum 32) | b64enc | quote }}