#!/bin/bash
# Script to install and use the Helm chart

echo "BrahminyKite Helm Chart Installation Guide"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "- Kubernetes cluster (minikube, kind, or cloud provider)"
echo "- kubectl configured to access your cluster"
echo "- Helm 3.x installed"
echo ""
echo "To install Helm (if not already installed):"
echo "  macOS:    brew install helm"
echo "  Linux:    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
echo "  Windows:  choco install kubernetes-helm"
echo ""
echo "Installation Steps:"
echo "1. Update Helm dependencies:"
echo "   cd helm/brahminykite"
echo "   helm dependency update"
echo ""
echo "2. Install the chart:"
echo "   # Development environment:"
echo "   helm install brahminykite . -f values-dev.yaml --create-namespace --namespace brahminykite-dev"
echo ""
echo "   # Production environment:"
echo "   helm install brahminykite . -f values-prod.yaml --create-namespace --namespace brahminykite"
echo ""
echo "3. Check the installation:"
echo "   helm list -A"
echo "   kubectl get pods -n brahminykite"
echo ""
echo "4. Access the services:"
echo "   # Port-forward the API:"
echo "   kubectl port-forward -n brahminykite svc/brahminykite-api 8000:8000"
echo ""
echo "   # Then visit http://localhost:8000/docs"
echo ""
echo "Uninstallation:"
echo "   helm uninstall brahminykite -n brahminykite"
echo "   kubectl delete namespace brahminykite"