apiVersion: v1
kind: ConfigMap
metadata:
  name: brahminykite-services-config
  namespace: brahminykite
  labels:
    app.kubernetes.io/name: brahminykite
    app.kubernetes.io/component: configuration
data:
  # Service configuration
  service_config.yaml: |
    services:
      empirical:
        port: 50051
        workers: 4
        max_connections: 100
        timeout: 30s
      contextual:
        port: 50052
        workers: 4
        max_connections: 100
        timeout: 30s
      consistency:
        port: 50053
        workers: 4
        max_connections: 100
        timeout: 30s
      power_dynamics:
        port: 50054
        workers: 4
        max_connections: 100
        timeout: 30s
      utility:
        port: 50055
        workers: 4
        max_connections: 100
        timeout: 30s
      evolution:
        port: 50056
        workers: 4
        max_connections: 100
        timeout: 30s
    
    database:
      host: postgres-service
      port: 5432
      name: brahminykite
      pool_size: 20
      max_overflow: 10
    
    redis:
      host: redis-service
      port: 6379
      max_connections: 50
      socket_timeout: 5
      socket_connect_timeout: 5
    
    monitoring:
      prometheus_port: 9090
      metrics_path: /metrics
      enable_tracing: true
      enable_profiling: false
  
  # Logging configuration
  logging.yaml: |
    version: 1
    disable_existing_loggers: false
    formatters:
      default:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      json:
        class: pythonjsonlogger.jsonlogger.JsonFormatter
        format: '%(asctime)s %(name)s %(levelname)s %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: default
        filename: /var/log/brahminykite/service.log
        maxBytes: 10485760  # 10MB
        backupCount: 3
    root:
      level: INFO
      handlers: [console, file]